---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: startpage
  namespace: web
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: startpage
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - startpage
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: front-end
        image: registry.analbeard.com/amd64/startpage:54dd359
        ports:
        - name: http-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 3
      imagePullSecrets:
      - name: private-registry-auth
