apiVersion: v1
kind: ServiceAccount
metadata:
  name: startpage-cache
  namespace: wealdy
  labels:
    owner: simonweald-at-giantswarm.io
    app.kubernetes.io/name: startpage
    app.kubernetes.io/component: startpage-cache
