apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: dockerhub-build
  labels:
    owner: simonweald-at-giantswarm.io
    app.kubernetes.io/name: dockerhub-build
spec:
  allowedCapabilities: [] # drop default capabilities
  allowPrivilegeEscalation: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
