---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simonweald-com
  namespace: shw
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: front-end
        image: registry.analbeard.com/website/simonweald:7dd62fa
        ports:
        - name: http-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 3
      imagePullSecrets:
      - name: registry-secret
