---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simonweald-com
  namespace: shw
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simonweald-com
    spec:
      containers:
      - name: front-end
        image: registry.analbeard.com/website/simonweald:7dd62fa
        ports:
        - name: http-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 3
      imagePullSecrets:
      - name: private-registry-auth
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simonweald-com-cache
  namespace: shw
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simonweald-com-cache
    spec:
      volumes:
      - name: varnish-config
        configMap:
          name: simonweald-com-vcl
          items:
          - key: default.vcl
            path: default.vcl
      containers:
      - name: varnish
        image: hermsi/alpine-varnish:6.1
        env:
        - name: VCL_CONFIG
          value: /etc/varnish/default.vcl
        volumeMounts:
        - name: varnish-config
          mountPath: /etc/varnish/
        ports:
        - name: varnish-port
          containerPort: 8080
