apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: www-simonweald-com
  namespace: web
spec:
  secretName: www-simonweald-com-tls
  duration: 2160h
  renewBefore: 360h
  commonName: www.simonweald.com
  dnsNames:
  - www.simonweald.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
