apiVersion: v1
kind: ServiceAccount
metadata:
  name: simonweald-cache
  namespace: wealdy
  labels:
    owner: simonweald-at-giantswarm.io
    app.kubernetes.io/name: simonweald
    app.kubernetes.io/component: simonweald-cache
