apiVersion: v1
kind: Service
metadata:
  name: simonweald-cache
  namespace: wealdy
  labels:
    owner: simonweald-at-giantswarm.io
    app.kubernetes.io/name: simonweald-cache
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: simonweald-cache
