apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: simonweald-web
  labels:
    owner: simonweald-at-giantswarm.io
    app.kubernetes.io/name: simonweald-web
spec:
  allowedCapabilities: [] # drop default capabilities
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  runAsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
