apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www.simonweald.com
  namespace: wealdy
  labels:
    owner: simonweald-at-giantswarm.io
    app.kubernetes.io/name: simonweald
    app.kubernetes.io/component: simonweald-web
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: "letsencrypt-wealdy"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - secretName: www-simonweald-com-tls
    hosts:
    - www.simonweald.com
  rules:
  - host: www.simonweald.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: simonweald-cache
            port:
              number: 80
