apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simonweald-web-psp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - simonweald-web
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simonweald-web-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simonweald-web-psp
subjects:
- kind: ServiceAccount
  name: simonweald-web
  namespace: wealdy
